---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: swe645-restAPI-deploy
  labels:
    app: swe645-restAPI-deploy
    test: test
#   annotations:
#     fluxcd.io/tag.example-app: semver:~1.0
#     fluxcd.io/automated: 'true'
spec:
  selector:
    matchLabels:
      app: swe645-restAPI-deploy
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: swe645-restAPI-deploy
    spec:
      containers:
      - name: swe645-restAPI-deploy
        image: ganeshmandava1247889/rest_api_provider:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8083


