---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-deploy
  labels:
    app: rest-app
    test: test
#   annotations:
#     fluxcd.io/tag.example-app: semver:~1.0
#     fluxcd.io/automated: 'true'
spec:
  selector:
    matchLabels:
      app: rest-app
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: rest-app
    spec:
      containers:
      - name: rest-app
        image: ganeshmandava1247889/rest_api_provider:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        # livenessProbe:
        #   httpGet:
        #     path: /status
        #     port: 5000
        #   initialDelaySeconds: 3
        #   periodSeconds: 3
#         resources:
#           requests:
#             memory: "64Mi"
#             cpu: "50m"
#           limits:
#             memory: "256Mi"
#             cpu: "500m"
