apiVersion: v1
kind: Service
metadata:
  name: rest-service
  labels:
    app: rest-app
spec:
  type: LoadBalancer
  selector:
    app: rest-app
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 8080
