apiVersion: v1
kind: Service
metadata:
  name: rest1-service
  labels:
    app: rest1-app
spec:
  type: LoadBalancer
  selector:
    app: rest1-app
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 8080
