apiVersion: v1
kind: Service
metadata:
  name: swe645-restapi-service
  labels:
    app: swe645-restapi-app
spec:
  type: LoadBalancer
  selector:
    app: swe645-restapi-app
  ports:
    - protocol: TCP
      name: rest
      port: 8080
